package com.tuluanix.mybatis.domain;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.LOGINNAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SEX
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.AGE
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PASSWORD
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SALT
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID
     *
     * @return the value of SYS_USER.ID
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID
     *
     * @param id the value for SYS_USER.ID
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.LOGINNAME
     *
     * @return the value of SYS_USER.LOGINNAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.LOGINNAME
     *
     * @param loginname the value for SYS_USER.LOGINNAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.NAME
     *
     * @return the value of SYS_USER.NAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.NAME
     *
     * @param name the value for SYS_USER.NAME
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.SEX
     *
     * @return the value of SYS_USER.SEX
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.SEX
     *
     * @param sex the value for SYS_USER.SEX
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.AGE
     *
     * @return the value of SYS_USER.AGE
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.AGE
     *
     * @param age the value for SYS_USER.AGE
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PASSWORD
     *
     * @return the value of SYS_USER.PASSWORD
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PASSWORD
     *
     * @param password the value for SYS_USER.PASSWORD
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.SALT
     *
     * @return the value of SYS_USER.SALT
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.SALT
     *
     * @param salt the value for SYS_USER.SALT
     *
     * @mbg.generated Sun Aug 13 22:59:30 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}